### ISSUE TITLE
As a dev, I need an environment

### ISSUE THREAD

**Issue by pixelfelt** [pixelfelt/pixelfelt#1]
## Scope
- [x] I can run `npm start` to start a local dev server
- [ ] I can run `npm run build` to build the project
- [ ] I can run `npm run deploy` to deploy to firebase

## Tasks
- [x] Start README
- [x] Setup Parcel.js
- [x] Setup an `src/index.pug` with favicon
- [ ] Add spectre.css
- [ ] Setup a basic coming soon landing page
